# Generated by Django 4.2.3 on 2023-09-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscore",
            name="aptest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userscore",
            name="engTest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userscore",
            name="selfTest",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
